### PR TITLE
Add Django 2.2 compatibility

### PR DESCRIPTION
**Pull request by rinti**
Fixes https://github.com/raiderrobert/django-multiurl/issues/34

### CODE REVIEW

**Comment by rinti** [comment]
Failing test is beacause it's tested against Django master with Python 3.5 which is not supported by Django 3.0.

**Comment by ramonakira** [comment]
Any progress on this? I kinda need Django 2.2 support right now ;-)

**Comment by rinti** [comment]
@raiderrobert Thanks for the great work on this application! If you feel you don't have the time for this project, would you be open to moving it to https://github.com/jazzband or adding a couple of maintainers on this repo and pypi?

**Comment by raiderrobert** [comment]
Oh very sorry. I can see about getting this in soon. Thanks for letting me
know!

**Comment by ramonakira** [comment]
Thanks very much! Looking forward to a new release ;)

**Comment by raiderrobert** [comment]
FYI, @ramonakira and @rinti I made a release on PyPI today

**Pull request merged**
